/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AppAuthenticatedTeacherRouteImport } from './routes/app/_authenticated/teacher'
import { Route as AppAuthenticatedSubjectsIndexRouteImport } from './routes/app/_authenticated/subjects/index'
import { Route as AppAuthenticatedQuizzesIndexRouteImport } from './routes/app/_authenticated/quizzes/index'
import { Route as AppAuthenticatedProfileIndexRouteImport } from './routes/app/_authenticated/profile/index'
import { Route as AppAuthenticatedLeaderboardsIndexRouteImport } from './routes/app/_authenticated/leaderboards/index'
import { Route as AppAuthenticatedClassIndexRouteImport } from './routes/app/_authenticated/class/index'
import { Route as AppAuthenticatedProfileUserIdRouteImport } from './routes/app/_authenticated/profile/$userId'
import { Route as AppAuthenticatedClassClassIdRouteImport } from './routes/app/_authenticated/class/$classId'
import { Route as AppAuthenticatedBadgesUserIdRouteImport } from './routes/app/_authenticated/badges/$userId'
import { Route as AppAuthenticatedTeacherQuizzesIndexRouteImport } from './routes/app/_authenticated/teacher/quizzes/index'
import { Route as AppAuthenticatedSubjectsSubjectIdIndexRouteImport } from './routes/app/_authenticated/subjects/$subjectId/index'
import { Route as AppAuthenticatedQuizzesQuizIdIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/index'
import { Route as AppAuthenticatedAdminUsersIndexRouteImport } from './routes/app/_authenticated/admin/users/index'
import { Route as AppAuthenticatedSubjectsSubjectIdQuizzesIndexRouteImport } from './routes/app/_authenticated/subjects/$subjectId/quizzes/index'
import { Route as AppAuthenticatedQuizzesQuizIdResultsIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/results/index'
import { Route as AppAuthenticatedQuizzesQuizIdPlayIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/play/index'
import { Route as AppAuthenticatedQuizzesQuizIdBuilderIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/builder/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedTeacherRoute = AppAuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedSubjectsIndexRoute =
  AppAuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesIndexRoute =
  AppAuthenticatedQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileIndexRoute =
  AppAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedLeaderboardsIndexRoute =
  AppAuthenticatedLeaderboardsIndexRouteImport.update({
    id: '/leaderboards/',
    path: '/leaderboards/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedClassIndexRoute =
  AppAuthenticatedClassIndexRouteImport.update({
    id: '/class/',
    path: '/class/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileUserIdRoute =
  AppAuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedClassClassIdRoute =
  AppAuthenticatedClassClassIdRouteImport.update({
    id: '/class/$classId',
    path: '/class/$classId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedBadgesUserIdRoute =
  AppAuthenticatedBadgesUserIdRouteImport.update({
    id: '/badges/$userId',
    path: '/badges/$userId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedTeacherQuizzesIndexRoute =
  AppAuthenticatedTeacherQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AppAuthenticatedTeacherRoute,
  } as any)
const AppAuthenticatedSubjectsSubjectIdIndexRoute =
  AppAuthenticatedSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdIndexRoute =
  AppAuthenticatedQuizzesQuizIdIndexRouteImport.update({
    id: '/quizzes/$quizId/',
    path: '/quizzes/$quizId/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedAdminUsersIndexRoute =
  AppAuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute =
  AppAuthenticatedSubjectsSubjectIdQuizzesIndexRouteImport.update({
    id: '/subjects/$subjectId/quizzes/',
    path: '/subjects/$subjectId/quizzes/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdResultsIndexRoute =
  AppAuthenticatedQuizzesQuizIdResultsIndexRouteImport.update({
    id: '/quizzes/$quizId/results/',
    path: '/quizzes/$quizId/results/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdPlayIndexRoute =
  AppAuthenticatedQuizzesQuizIdPlayIndexRouteImport.update({
    id: '/quizzes/$quizId/play/',
    path: '/quizzes/$quizId/play/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdBuilderIndexRoute =
  AppAuthenticatedQuizzesQuizIdBuilderIndexRouteImport.update({
    id: '/quizzes/$quizId/builder/',
    path: '/quizzes/$quizId/builder/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/teacher': typeof AppAuthenticatedTeacherRouteWithChildren
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/badges/$userId': typeof AppAuthenticatedBadgesUserIdRoute
  '/app/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/class/': typeof AppAuthenticatedClassIndexRoute
  '/app/leaderboards/': typeof AppAuthenticatedLeaderboardsIndexRoute
  '/app/profile/': typeof AppAuthenticatedProfileIndexRoute
  '/app/quizzes/': typeof AppAuthenticatedQuizzesIndexRoute
  '/app/subjects/': typeof AppAuthenticatedSubjectsIndexRoute
  '/app/admin/users/': typeof AppAuthenticatedAdminUsersIndexRoute
  '/app/quizzes/$quizId/': typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  '/app/subjects/$subjectId/': typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  '/app/teacher/quizzes/': typeof AppAuthenticatedTeacherQuizzesIndexRoute
  '/app/quizzes/$quizId/builder/': typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  '/app/quizzes/$quizId/play/': typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  '/app/quizzes/$quizId/results/': typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  '/app/subjects/$subjectId/quizzes/': typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/register': typeof RegisterIndexRoute
  '/app/teacher': typeof AppAuthenticatedTeacherRouteWithChildren
  '/app': typeof AppAuthenticatedIndexRoute
  '/app/badges/$userId': typeof AppAuthenticatedBadgesUserIdRoute
  '/app/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/class': typeof AppAuthenticatedClassIndexRoute
  '/app/leaderboards': typeof AppAuthenticatedLeaderboardsIndexRoute
  '/app/profile': typeof AppAuthenticatedProfileIndexRoute
  '/app/quizzes': typeof AppAuthenticatedQuizzesIndexRoute
  '/app/subjects': typeof AppAuthenticatedSubjectsIndexRoute
  '/app/admin/users': typeof AppAuthenticatedAdminUsersIndexRoute
  '/app/quizzes/$quizId': typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  '/app/subjects/$subjectId': typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  '/app/teacher/quizzes': typeof AppAuthenticatedTeacherQuizzesIndexRoute
  '/app/quizzes/$quizId/builder': typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  '/app/quizzes/$quizId/play': typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  '/app/quizzes/$quizId/results': typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  '/app/subjects/$subjectId/quizzes': typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/_authenticated/teacher': typeof AppAuthenticatedTeacherRouteWithChildren
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/badges/$userId': typeof AppAuthenticatedBadgesUserIdRoute
  '/app/_authenticated/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/_authenticated/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/_authenticated/class/': typeof AppAuthenticatedClassIndexRoute
  '/app/_authenticated/leaderboards/': typeof AppAuthenticatedLeaderboardsIndexRoute
  '/app/_authenticated/profile/': typeof AppAuthenticatedProfileIndexRoute
  '/app/_authenticated/quizzes/': typeof AppAuthenticatedQuizzesIndexRoute
  '/app/_authenticated/subjects/': typeof AppAuthenticatedSubjectsIndexRoute
  '/app/_authenticated/admin/users/': typeof AppAuthenticatedAdminUsersIndexRoute
  '/app/_authenticated/quizzes/$quizId/': typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  '/app/_authenticated/subjects/$subjectId/': typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  '/app/_authenticated/teacher/quizzes/': typeof AppAuthenticatedTeacherQuizzesIndexRoute
  '/app/_authenticated/quizzes/$quizId/builder/': typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  '/app/_authenticated/quizzes/$quizId/play/': typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  '/app/_authenticated/quizzes/$quizId/results/': typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  '/app/_authenticated/subjects/$subjectId/quizzes/': typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login/'
    | '/logout/'
    | '/register/'
    | '/app/teacher'
    | '/app/'
    | '/app/badges/$userId'
    | '/app/class/$classId'
    | '/app/profile/$userId'
    | '/app/class/'
    | '/app/leaderboards/'
    | '/app/profile/'
    | '/app/quizzes/'
    | '/app/subjects/'
    | '/app/admin/users/'
    | '/app/quizzes/$quizId/'
    | '/app/subjects/$subjectId/'
    | '/app/teacher/quizzes/'
    | '/app/quizzes/$quizId/builder/'
    | '/app/quizzes/$quizId/play/'
    | '/app/quizzes/$quizId/results/'
    | '/app/subjects/$subjectId/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/app/teacher'
    | '/app'
    | '/app/badges/$userId'
    | '/app/class/$classId'
    | '/app/profile/$userId'
    | '/app/class'
    | '/app/leaderboards'
    | '/app/profile'
    | '/app/quizzes'
    | '/app/subjects'
    | '/app/admin/users'
    | '/app/quizzes/$quizId'
    | '/app/subjects/$subjectId'
    | '/app/teacher/quizzes'
    | '/app/quizzes/$quizId/builder'
    | '/app/quizzes/$quizId/play'
    | '/app/quizzes/$quizId/results'
    | '/app/subjects/$subjectId/quizzes'
  id:
    | '__root__'
    | '/'
    | '/app/_authenticated'
    | '/login/'
    | '/logout/'
    | '/register/'
    | '/app/_authenticated/teacher'
    | '/app/_authenticated/'
    | '/app/_authenticated/badges/$userId'
    | '/app/_authenticated/class/$classId'
    | '/app/_authenticated/profile/$userId'
    | '/app/_authenticated/class/'
    | '/app/_authenticated/leaderboards/'
    | '/app/_authenticated/profile/'
    | '/app/_authenticated/quizzes/'
    | '/app/_authenticated/subjects/'
    | '/app/_authenticated/admin/users/'
    | '/app/_authenticated/quizzes/$quizId/'
    | '/app/_authenticated/subjects/$subjectId/'
    | '/app/_authenticated/teacher/quizzes/'
    | '/app/_authenticated/quizzes/$quizId/builder/'
    | '/app/_authenticated/quizzes/$quizId/play/'
    | '/app/_authenticated/quizzes/$quizId/results/'
    | '/app/_authenticated/subjects/$subjectId/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/teacher': {
      id: '/app/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/app/teacher'
      preLoaderRoute: typeof AppAuthenticatedTeacherRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/subjects/': {
      id: '/app/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/app/subjects/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/': {
      id: '/app/_authenticated/quizzes/'
      path: '/quizzes'
      fullPath: '/app/quizzes/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/': {
      id: '/app/_authenticated/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppAuthenticatedProfileIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/leaderboards/': {
      id: '/app/_authenticated/leaderboards/'
      path: '/leaderboards'
      fullPath: '/app/leaderboards/'
      preLoaderRoute: typeof AppAuthenticatedLeaderboardsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/class/': {
      id: '/app/_authenticated/class/'
      path: '/class'
      fullPath: '/app/class/'
      preLoaderRoute: typeof AppAuthenticatedClassIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/$userId': {
      id: '/app/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/app/profile/$userId'
      preLoaderRoute: typeof AppAuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/class/$classId': {
      id: '/app/_authenticated/class/$classId'
      path: '/class/$classId'
      fullPath: '/app/class/$classId'
      preLoaderRoute: typeof AppAuthenticatedClassClassIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/badges/$userId': {
      id: '/app/_authenticated/badges/$userId'
      path: '/badges/$userId'
      fullPath: '/app/badges/$userId'
      preLoaderRoute: typeof AppAuthenticatedBadgesUserIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/teacher/quizzes/': {
      id: '/app/_authenticated/teacher/quizzes/'
      path: '/quizzes'
      fullPath: '/app/teacher/quizzes/'
      preLoaderRoute: typeof AppAuthenticatedTeacherQuizzesIndexRouteImport
      parentRoute: typeof AppAuthenticatedTeacherRoute
    }
    '/app/_authenticated/subjects/$subjectId/': {
      id: '/app/_authenticated/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/': {
      id: '/app/_authenticated/quizzes/$quizId/'
      path: '/quizzes/$quizId'
      fullPath: '/app/quizzes/$quizId/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/admin/users/': {
      id: '/app/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/subjects/$subjectId/quizzes/': {
      id: '/app/_authenticated/subjects/$subjectId/quizzes/'
      path: '/subjects/$subjectId/quizzes'
      fullPath: '/app/subjects/$subjectId/quizzes/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/results/': {
      id: '/app/_authenticated/quizzes/$quizId/results/'
      path: '/quizzes/$quizId/results'
      fullPath: '/app/quizzes/$quizId/results/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdResultsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/play/': {
      id: '/app/_authenticated/quizzes/$quizId/play/'
      path: '/quizzes/$quizId/play'
      fullPath: '/app/quizzes/$quizId/play/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdPlayIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/builder/': {
      id: '/app/_authenticated/quizzes/$quizId/builder/'
      path: '/quizzes/$quizId/builder'
      fullPath: '/app/quizzes/$quizId/builder/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AppAuthenticatedTeacherRouteChildren {
  AppAuthenticatedTeacherQuizzesIndexRoute: typeof AppAuthenticatedTeacherQuizzesIndexRoute
}

const AppAuthenticatedTeacherRouteChildren: AppAuthenticatedTeacherRouteChildren =
  {
    AppAuthenticatedTeacherQuizzesIndexRoute:
      AppAuthenticatedTeacherQuizzesIndexRoute,
  }

const AppAuthenticatedTeacherRouteWithChildren =
  AppAuthenticatedTeacherRoute._addFileChildren(
    AppAuthenticatedTeacherRouteChildren,
  )

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedTeacherRoute: typeof AppAuthenticatedTeacherRouteWithChildren
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedBadgesUserIdRoute: typeof AppAuthenticatedBadgesUserIdRoute
  AppAuthenticatedClassClassIdRoute: typeof AppAuthenticatedClassClassIdRoute
  AppAuthenticatedProfileUserIdRoute: typeof AppAuthenticatedProfileUserIdRoute
  AppAuthenticatedClassIndexRoute: typeof AppAuthenticatedClassIndexRoute
  AppAuthenticatedLeaderboardsIndexRoute: typeof AppAuthenticatedLeaderboardsIndexRoute
  AppAuthenticatedProfileIndexRoute: typeof AppAuthenticatedProfileIndexRoute
  AppAuthenticatedQuizzesIndexRoute: typeof AppAuthenticatedQuizzesIndexRoute
  AppAuthenticatedSubjectsIndexRoute: typeof AppAuthenticatedSubjectsIndexRoute
  AppAuthenticatedAdminUsersIndexRoute: typeof AppAuthenticatedAdminUsersIndexRoute
  AppAuthenticatedQuizzesQuizIdIndexRoute: typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  AppAuthenticatedSubjectsSubjectIdIndexRoute: typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  AppAuthenticatedQuizzesQuizIdBuilderIndexRoute: typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  AppAuthenticatedQuizzesQuizIdPlayIndexRoute: typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  AppAuthenticatedQuizzesQuizIdResultsIndexRoute: typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute: typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedTeacherRoute: AppAuthenticatedTeacherRouteWithChildren,
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedBadgesUserIdRoute: AppAuthenticatedBadgesUserIdRoute,
  AppAuthenticatedClassClassIdRoute: AppAuthenticatedClassClassIdRoute,
  AppAuthenticatedProfileUserIdRoute: AppAuthenticatedProfileUserIdRoute,
  AppAuthenticatedClassIndexRoute: AppAuthenticatedClassIndexRoute,
  AppAuthenticatedLeaderboardsIndexRoute:
    AppAuthenticatedLeaderboardsIndexRoute,
  AppAuthenticatedProfileIndexRoute: AppAuthenticatedProfileIndexRoute,
  AppAuthenticatedQuizzesIndexRoute: AppAuthenticatedQuizzesIndexRoute,
  AppAuthenticatedSubjectsIndexRoute: AppAuthenticatedSubjectsIndexRoute,
  AppAuthenticatedAdminUsersIndexRoute: AppAuthenticatedAdminUsersIndexRoute,
  AppAuthenticatedQuizzesQuizIdIndexRoute:
    AppAuthenticatedQuizzesQuizIdIndexRoute,
  AppAuthenticatedSubjectsSubjectIdIndexRoute:
    AppAuthenticatedSubjectsSubjectIdIndexRoute,
  AppAuthenticatedQuizzesQuizIdBuilderIndexRoute:
    AppAuthenticatedQuizzesQuizIdBuilderIndexRoute,
  AppAuthenticatedQuizzesQuizIdPlayIndexRoute:
    AppAuthenticatedQuizzesQuizIdPlayIndexRoute,
  AppAuthenticatedQuizzesQuizIdResultsIndexRoute:
    AppAuthenticatedQuizzesQuizIdResultsIndexRoute,
  AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute:
    AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
