/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AppAuthenticatedSubjectsIndexRouteImport } from './routes/app/_authenticated/subjects/index'
import { Route as AppAuthenticatedProfileIndexRouteImport } from './routes/app/_authenticated/profile/index'
import { Route as AppAuthenticatedClassIndexRouteImport } from './routes/app/_authenticated/class/index'
import { Route as AppAuthenticatedSubjectsSubjectIdRouteImport } from './routes/app/_authenticated/subjects/$subjectId'
import { Route as AppAuthenticatedProfileUserIdRouteImport } from './routes/app/_authenticated/profile/$userId'
import { Route as AppAuthenticatedClassClassIdRouteImport } from './routes/app/_authenticated/class/$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedSubjectsIndexRoute =
  AppAuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileIndexRoute =
  AppAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedClassIndexRoute =
  AppAuthenticatedClassIndexRouteImport.update({
    id: '/class/',
    path: '/class/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedSubjectsSubjectIdRoute =
  AppAuthenticatedSubjectsSubjectIdRouteImport.update({
    id: '/subjects/$subjectId',
    path: '/subjects/$subjectId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileUserIdRoute =
  AppAuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedClassClassIdRoute =
  AppAuthenticatedClassClassIdRouteImport.update({
    id: '/class/$classId',
    path: '/class/$classId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/subjects/$subjectId': typeof AppAuthenticatedSubjectsSubjectIdRoute
  '/app/class/': typeof AppAuthenticatedClassIndexRoute
  '/app/profile/': typeof AppAuthenticatedProfileIndexRoute
  '/app/subjects/': typeof AppAuthenticatedSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/register': typeof RegisterIndexRoute
  '/app': typeof AppAuthenticatedIndexRoute
  '/app/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/subjects/$subjectId': typeof AppAuthenticatedSubjectsSubjectIdRoute
  '/app/class': typeof AppAuthenticatedClassIndexRoute
  '/app/profile': typeof AppAuthenticatedProfileIndexRoute
  '/app/subjects': typeof AppAuthenticatedSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/_authenticated/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/_authenticated/subjects/$subjectId': typeof AppAuthenticatedSubjectsSubjectIdRoute
  '/app/_authenticated/class/': typeof AppAuthenticatedClassIndexRoute
  '/app/_authenticated/profile/': typeof AppAuthenticatedProfileIndexRoute
  '/app/_authenticated/subjects/': typeof AppAuthenticatedSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login/'
    | '/logout/'
    | '/register/'
    | '/app/'
    | '/app/class/$classId'
    | '/app/profile/$userId'
    | '/app/subjects/$subjectId'
    | '/app/class/'
    | '/app/profile/'
    | '/app/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/app'
    | '/app/class/$classId'
    | '/app/profile/$userId'
    | '/app/subjects/$subjectId'
    | '/app/class'
    | '/app/profile'
    | '/app/subjects'
  id:
    | '__root__'
    | '/'
    | '/app/_authenticated'
    | '/login/'
    | '/logout/'
    | '/register/'
    | '/app/_authenticated/'
    | '/app/_authenticated/class/$classId'
    | '/app/_authenticated/profile/$userId'
    | '/app/_authenticated/subjects/$subjectId'
    | '/app/_authenticated/class/'
    | '/app/_authenticated/profile/'
    | '/app/_authenticated/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/subjects/': {
      id: '/app/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/app/subjects/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/': {
      id: '/app/_authenticated/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppAuthenticatedProfileIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/class/': {
      id: '/app/_authenticated/class/'
      path: '/class'
      fullPath: '/app/class/'
      preLoaderRoute: typeof AppAuthenticatedClassIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/subjects/$subjectId': {
      id: '/app/_authenticated/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId'
      preLoaderRoute: typeof AppAuthenticatedSubjectsSubjectIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/$userId': {
      id: '/app/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/app/profile/$userId'
      preLoaderRoute: typeof AppAuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/class/$classId': {
      id: '/app/_authenticated/class/$classId'
      path: '/class/$classId'
      fullPath: '/app/class/$classId'
      preLoaderRoute: typeof AppAuthenticatedClassClassIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
  }
}

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedClassClassIdRoute: typeof AppAuthenticatedClassClassIdRoute
  AppAuthenticatedProfileUserIdRoute: typeof AppAuthenticatedProfileUserIdRoute
  AppAuthenticatedSubjectsSubjectIdRoute: typeof AppAuthenticatedSubjectsSubjectIdRoute
  AppAuthenticatedClassIndexRoute: typeof AppAuthenticatedClassIndexRoute
  AppAuthenticatedProfileIndexRoute: typeof AppAuthenticatedProfileIndexRoute
  AppAuthenticatedSubjectsIndexRoute: typeof AppAuthenticatedSubjectsIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedClassClassIdRoute: AppAuthenticatedClassClassIdRoute,
  AppAuthenticatedProfileUserIdRoute: AppAuthenticatedProfileUserIdRoute,
  AppAuthenticatedSubjectsSubjectIdRoute:
    AppAuthenticatedSubjectsSubjectIdRoute,
  AppAuthenticatedClassIndexRoute: AppAuthenticatedClassIndexRoute,
  AppAuthenticatedProfileIndexRoute: AppAuthenticatedProfileIndexRoute,
  AppAuthenticatedSubjectsIndexRoute: AppAuthenticatedSubjectsIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
